sudo: required
os: linux
group: edge

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libdbus-1-dev

language: rust

matrix:
    allow_failures:
        - env: TASK=clippy
    include:
        - rust: stable
          env: TASK=fmt
        - rust: stable
          env: TASK=build
        - rust: stable
          env: TASK=docs
        - rust: stable
          env: TASK=test
        - rust: stable
          env: TASK=test-loop
        - rust: nightly
          env: TASK=clippy

branches:
    only: master

script: make -f Makefile $TASK
