os: linux
group: edge

addons:
    apt:
        packages:
          - libdbus-1-dev
          - libudev-dev

language: rust

matrix:
    include:
        - rust: stable
          env: TASK=travis_fmt
        - rust: stable
          env: TASK=build
        - rust: stable
          env: TASK=docs
        - rust: stable
          env: TASK=test
        - rust: stable
          env: TASK=test-travis
          sudo: required
        - rust: nightly
          env: TASK=clippy

branches:
    only: master

script: make -f Makefile $TASK
