os: linux
group: edge

addons:
    apt:
        packages:
            libdbus-1-dev

language: rust

matrix:
    include:
        - rust: stable
          env: TASK=fmt
        - rust: stable
          env: TASK=build
        - rust: stable
          env: TASK=docs
        - rust: stable
          env: TASK=test
        - rust: stable
          sudo: required
          env: TASK=test-loop
        - rust: nightly
          env: TASK=clippy

branches:
    only: master

script: make -f Makefile $TASK
