[package]
name = "stratisd"
version = "0.1.0"
authors = ["Todd Gill <tgill@redhat.com>", "Andy Grover <agrover@redhat.com>"]


[dependencies]
dbus = "0.3"
clap = "1"
nix = "0"
devicemapper = "0.4.0"
crc = "1"
byteorder = "0.3.13"
uuid = "0.1.18"
time = "0.1"
bytesize = "0.1.1"
newtype_derive = "0.1"
custom_derive = "0.1"
term = "0.4"